// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/pbfile/common.proto

package pbfile

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pager struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageNum              int64    `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	TotalRows            int64    `protobuf:"varint,3,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pager) Reset()         { *m = Pager{} }
func (m *Pager) String() string { return proto.CompactTextString(m) }
func (*Pager) ProtoMessage()    {}
func (*Pager) Descriptor() ([]byte, []int) {
	return fileDescriptor_26d4f5cee1e61aab, []int{0}
}

func (m *Pager) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pager.Unmarshal(m, b)
}
func (m *Pager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pager.Marshal(b, m, deterministic)
}
func (m *Pager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pager.Merge(m, src)
}
func (m *Pager) XXX_Size() int {
	return xxx_messageInfo_Pager.Size(m)
}
func (m *Pager) XXX_DiscardUnknown() {
	xxx_messageInfo_Pager.DiscardUnknown(m)
}

var xxx_messageInfo_Pager proto.InternalMessageInfo

func (m *Pager) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Pager) GetPageNum() int64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *Pager) GetTotalRows() int64 {
	if m != nil {
		return m.TotalRows
	}
	return 0
}

func init() {
	proto.RegisterType((*Pager)(nil), "pbfile.Pager")
}

func init() { proto.RegisterFile("grpc/pbfile/common.proto", fileDescriptor_26d4f5cee1e61aab) }

var fileDescriptor_26d4f5cee1e61aab = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x48, 0x2f, 0x2a, 0x48,
	0xd6, 0x2f, 0x48, 0x4a, 0xcb, 0xcc, 0x49, 0xd5, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0xd3, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0x08, 0x2a, 0x85, 0x72, 0xb1, 0x06, 0x24, 0xa6, 0xa7,
	0x16, 0x09, 0x09, 0x71, 0xb1, 0x14, 0x24, 0xa6, 0xa7, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07,
	0x81, 0xd9, 0x42, 0x92, 0x5c, 0x1c, 0x20, 0x3a, 0x3e, 0xaf, 0x34, 0x57, 0x82, 0x09, 0x2c, 0xce,
	0x0e, 0xe2, 0xfb, 0x95, 0xe6, 0x0a, 0xc9, 0x72, 0x71, 0x95, 0xe4, 0x97, 0x24, 0xe6, 0xc4, 0x17,
	0xe5, 0x97, 0x17, 0x4b, 0x30, 0x83, 0x25, 0x39, 0xc1, 0x22, 0x41, 0xf9, 0xe5, 0xc5, 0x49, 0x6c,
	0x60, 0x5b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb5, 0xcf, 0x11, 0xff, 0x81, 0x00, 0x00,
	0x00,
}
